FROM golang:1.9.2
LABEL authors="Mat Baker <mbaker@cozero.com.au>,Stuart Auld <sauld@cozero.com.au>"

# Use dep to convert vendor.json to Gopkg.lock and then update with our Gopkg.toml
# Warning: using master until v0.3.3 is released!
ENV GOLANG_DEP_VERSION master

RUN \
     go get -u github.com/golang/dep/cmd/dep \
  && cd $GOPATH/src/github.com/golang/dep \
  && git checkout $GOLANG_DEP_VERSION \
# Create our app folder
  && mkdir -p $GOPATH/src/app

WORKDIR $GOPATH/src/app

RUN \
     dep init -v

COPY hello Gopkg.toml ./

RUN dep ensure -v

CMD ["cat", "Gopkg.lock"]
