
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.10"

[[constraint]]
  name = "github.com/cozero/terraform-provider-aws"
  version = "0.1.4"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  # currently this is the only known working commitish
  # this terraform commit breaks 4acdc53a5646aef7fd1f5044ffb6c1380687344b acceptance testing
  revision = "d969f97e730d527a568a0929ce52df70e062bca0"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "1.0.0"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-tls"
  version = "1.0.0"
