[metadata]
project = "arrakis-acceptance-testing"
updated = "2017-12-04"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  # locked to master until the 0.11.2 release
  branch = "master"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "1.6.0"

  [[constraint]]
    name = "github.com/terraform-providers/terraform-provider-template"
    version = "1.0.0"
