[metadata]
project = "arrakis-acceptance-testing"
updated = "2018-02-02"

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "^0.11.7"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-archive"
  version = "^1.0.3"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "^1.13"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-pagerduty"
  version = "^1.0"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-random"
  version = "^1.2"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "^1.0"
