[metadata]
project = "arrakis-acceptance-testing"
updated = "2017-12-04"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  # version = "=0.11.1"
  branch = "module-test-helpers"
  source = "github.com/cozero/terraform"
