[metadata]
project = "arrakis-acceptance-testing"
updated = "2018-02-02"

[[override]]
  name = "github.com/hashicorp/terraform"
  revision = "2a503b6"
  source = "https://github.com/cozero/terraform"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "1.9.0"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "1.0.0"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-pagerduty"
  version = "0.1.3"
