
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/hashicorp/terraform/helper/acctest",
            "github.com/hashicorp/terraform/helper/schema",
            "github.com/hashicorp/terraform/helper/resource",
            "github.com/hashicorp/terraform/terraform",
            "github.com/terraform-providers/terraform-provider-aws/aws",
            "github.com/terraform-providers/terraform-provider-template/template",
            "github.com/terraform-providers/terraform-provider-tls/tls",
            "github.com/aws/aws-sdk-go/aws",
            "github.com/aws/aws-sdk-go/aws/awserr",
            "github.com/aws/aws-sdk-go/service/iam",
            "github.com/aws/aws-sdk-go/service/route53"]
[metadata]
project = "arrakis"
updated = "2017-10-16"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.10"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "=0.10.7-acceptance-testing"
  # this hashicorp terraform commit 4acdc53a5646aef7fd1f5044ffb6c1380687344b
  # makes id fields illegal, breaking acceptance testing. it will be fixed when
  # terraform-provider-aws removes id fields from their resources.
  source = "github.com/cozero/terraform"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "1.1.0"
  # eventually the cozero fork should die. when
	# https://github.com/terraform-providers/terraform-provider-aws/pull/1463
	# gets merged remove this source
  source = "github.com/cozero/terraform-provider-aws"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "1.0.0"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-tls"
  version = "1.0.0"
