[metadata]
project = "arrakis-acceptance-testing"
updated = "2018-02-02"

[[override]]
  name = "github.com/hashicorp/terraform"
  revision = "1d0f5fdac99ec9f1a8269aded78ce1da6f547fab"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-archive"
  version = "^1.0"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "^1.10"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-pagerduty"
  version = "^0.1"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-random"
  version = "^1.1"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "^1.0"
