[metadata]
project = "arrakis-acceptance-testing"
updated = "2018-07-16"

# aws-sdk-go has changes in v1.14.25 onwards that altered.
# Further, the vendor.json in the terraform-provider-aws is not valid.
# https://github.com/terraform-providers/terraform-provider-aws/blob/v1.27.0/vendor/vendor.json
[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.14.24"

[[override]]
  name = "github.com/hashicorp/terraform"
  version = "^0.11.7"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-archive"
  version = "^1.0.3"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "^1.27"

[[override]]
  name = "github.com/cozero/terraform-provider-buildkite"
  version = "^0.0"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-grafana"
  version = "^1.0"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-github"
  version = "^1.1"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-pagerduty"
  version = "^1.1"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-random"
  version = "^1.3"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "^1.0"
